### ISSUE TITLE
Use char instead of int for memory

### ISSUE THREAD

**Issue by itchyny** [apankrat/bff#1]
I've been enjoying writing Brainf**k code but I found that ideone sometimes costs too much time executing my program (http://ideone.com/P6IKHo, http://ideone.com/l5oQyD for example).
And I've got to know the interpreter used in ideone is here.

The problem was bff uses `int` for the register variable `v`.
I have assumed it was `char`.

I looked into the wikipedia article and also into the esolangs.org article, they say '8-bit size is still the common size' or 'Most implementations do likewise (as the original implementation)'.
Shouldn't bff follow this in honor of the original one?

What do you think?

**Comment by apankrat** [comment]
Oh sorry, @itchyny, this one slipped under the radar. I'd rather not make this change, because it's not backward compatible. Perhaps have a compile time option instead?

**Comment by itchyny** [comment]
I hope this behaviour will be fixed and ideone updates the interpreter anyway. Assuming the interpreter running under modulo 256 makes me write a code easy.
